#receivers:
#  jaeger:
#    protocols:
#      grpc:
#      thrift_http:
#      thrift_tchannel:
#      thrift_compact:
#      thrift_binary:
#exporters:
#  jaeger_grpc:#    endpoint: "http://localhost:14250"
#extensions:
#  health_check: {}
#    pprof: {}
#    zpages: {}
#service:
#  extensions: [health_check, pprof, zpages]
#  pipelines:
#    traces:
#      receivers: [jaeger]
#      processors: [batch, queued_retry]
#      exporters: [jaeger]