version: '3'

services:
  opentelemetry:
    image: pkerbynn/opentelemetry:latest
    ports:
      - "2020:2020"
    environment:
      - JAEGER_SERVICE_NAME=myopentelemetryservice
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    depends_on:
      - jaegertracing
      restart: on-failure

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"